# Generated by Django 4.2.5 on 2023-10-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس:',
                'verbose_name_plural': 'اطلاعات تماس:',
            },
        ),
        migrations.CreateModel(
            name='dataToAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='مقدار')),
                ('d', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websiteInfo.accessinfo')),
            ],
            options={
                'verbose_name': 'اطلاعاتی که میخواهید در پایین سایت نمایش دهید:',
                'verbose_name_plural': 'اطلاعاتی که میخواهید در پایین سایت نمایش دهید:',
            },
        ),
        migrations.DeleteModel(
            name='phoneNumber',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس'},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'توضیحاتی که می خواهید در پایین سایت نمایش دهید:', 'verbose_name_plural': 'توضیحاتی که می خواهید در پایین سایت نمایش دهید:'},
        ),
    ]
