# Generated by Django 4.2.5 on 2023-10-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteInfo', '0002_accessinfo_datatoaccess_delete_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatoaccess',
            old_name='text',
            new_name='value',
        ),
        migrations.AddField(
            model_name='datatoaccess',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
