# Generated by Django 4.2.5 on 2023-11-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteInfo', '0003_rename_text_datatoaccess_value_datatoaccess_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='تایتل درباره ی ما')),
                ('content', models.CharField(blank=True, max_length=2000, null=True, verbose_name='محتوای درباره ی ما')),
            ],
            options={
                'verbose_name': 'بخش درباره ی ما',
                'verbose_name_plural': 'بخش درباره ی ما',
            },
        ),
    ]
