# Generated by Django 4.2.5 on 2023-09-23 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته بندی')),
                ('img', models.ImageField(upload_to='', verbose_name='تصویر دسته بندی')),
            ],
            options={
                'verbose_name': 'تقسیم بندی ها',
                'verbose_name_plural': 'تقسیم بندی ها',
            },
        ),
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'لوگو',
                'verbose_name_plural': 'لوگو',
            },
        ),
        migrations.CreateModel(
            name='Ord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityId', models.CharField(max_length=10, null=True)),
                ('cityAndStateName', models.CharField(max_length=1000, null=True)),
                ('postalCode', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(choices=[('p', 'در حال ارسال'), ('F', 'ارسال شده'), ('C', 'لغو شده')], default='p', max_length=100, verbose_name='وضعیت ارسال')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارشات',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='تصویر محصول')),
                ('title', models.CharField(max_length=300, verbose_name='تایتل')),
                ('pricing', models.IntegerField(verbose_name='قیمت')),
                ('discount', models.IntegerField(default=0, verbose_name='میزان تخفیف %')),
                ('introduction', models.CharField(max_length=1500, verbose_name='درباره محصول (بخش معرفی)')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.division', verbose_name='یکی از تقسیم بندی ها رو انتخاب کنید')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول',
            },
        ),
        migrations.CreateModel(
            name='registeredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='نام زیر دسته بندی')),
            ],
            options={
                'verbose_name': 'زیر تقسیم بندی ها',
                'verbose_name_plural': 'زیر تقسیم بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='مشخصه')),
                ('Prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.product')),
            ],
            options={
                'verbose_name': 'مشخصه',
                'verbose_name_plural': 'بخش مشخصات در صفحه محصول',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='digitalAssets/frontEnd/images//', verbose_name='تصویر اسلایدر')),
                ('Prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontEnd.product')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontEnd.division')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر',
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=120, null=True)),
                ('lastName', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشتریان احتمالی',
                'verbose_name_plural': 'مشتریان احتمالی',
            },
        ),
        migrations.CreateModel(
            name='productsInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('explainations', models.CharField(max_length=1000, null=True)),
                ('chainPosition', models.CharField(max_length=1000, null=True)),
                ('installationPosition', models.CharField(max_length=1000, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontEnd.ord')),
                ('prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontEnd.product')),
            ],
            options={
                'verbose_name': 'محصولات',
                'verbose_name_plural': 'اجزاء سبد خرید',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subDivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontEnd.subdivision', verbose_name='(انتخابی) یکی از زیر تقسیم بندی ها رو انتخاب کنید'),
        ),
        migrations.CreateModel(
            name='prodToProfwhore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.product')),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.profile')),
            ],
            options={
                'verbose_name': 'محصولات خریداری شده:',
                'verbose_name_plural': 'محصولات خریداری شده:',
            },
        ),
        migrations.CreateModel(
            name='mainThird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('div', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontEnd.division', verbose_name='تقسیم بندی')),
                ('prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontEnd.product', verbose_name='محصول')),
                ('subDiv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontEnd.subdivision', verbose_name='زیر تقسیم بندی')),
            ],
            options={
                'verbose_name': 'تصویر سوم منوی اصلی:',
                'verbose_name_plural': 'تصویر سوم منوی اصلی:',
            },
        ),
        migrations.CreateModel(
            name='mainTableFirstPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('div', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontEnd.division', verbose_name='تقسیم بندی')),
                ('prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontEnd.product', verbose_name='محصول')),
                ('subDiv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontEnd.subdivision', verbose_name='زیر تقسیم بندی')),
            ],
            options={
                'verbose_name': 'تصویر اول منوی اصلی:',
                'verbose_name_plural': 'تصویر اول منوی اصلی:',
            },
        ),
        migrations.CreateModel(
            name='mainSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('div', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontEnd.division', verbose_name='تقسیم بندی')),
                ('prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontEnd.product', verbose_name='محصول')),
                ('subDiv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontEnd.subdivision', verbose_name='زیر تقسیم بندی')),
            ],
            options={
                'verbose_name': 'تصاویر دوم منوی اصلی:',
                'verbose_name_plural': 'تصاویر دوم منوی اصلی:',
            },
        ),
        migrations.CreateModel(
            name='giveOrd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontEnd.ord')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontEnd.profile')),
            ],
        ),
        migrations.CreateModel(
            name='fetures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='ویژگی')),
                ('Prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.product')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'بخش ویژگی ها در صفحه محصول',
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, editable=False, max_length=800, null=True, verbose_name='کامنت')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontEnd.profile')),
                ('product', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontEnd.product')),
            ],
            options={
                'verbose_name': 'کامنت ها:',
                'verbose_name_plural': 'کامنت ها:',
            },
        ),
    ]
