# Generated by Django 4.2.4 on 2023-08-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontEnd", "0002_alter_logo_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logo",
            name="logo",
            field=models.ImageField(upload_to="digitalAssets/frontEnd/images"),
        ),
    ]
