# Generated by Django 4.2.5 on 2023-10-10 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0002_alter_comment_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='تصویر محصول')),
                ('p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontEnd.product')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصویر محصول',
            },
        ),
    ]
