# Generated by Django 4.2.4 on 2023-08-22 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontEnd", "0003_alter_logo_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logo",
            options={
                "verbose_name": "Custom Model Name",
                "verbose_name_plural": "Custom Model Names",
            },
        ),
    ]
