# Generated by Django 4.2.4 on 2023-08-22 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontEnd", "0005_alter_logo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logo",
            options={"verbose_name": "لوگو", "verbose_name_plural": "لوگو"},
        ),
    ]
