# Generated by Django 4.2.4 on 2023-08-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontEnd", "0006_alter_logo_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="digitalAssets/frontEnd/images")),
                ("title", models.CharField(max_length=300)),
                ("pricing", models.IntegerField()),
                ("introduction", models.CharField(max_length=1500)),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصول",
            },
        ),
        migrations.CreateModel(
            name="Specs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                (
                    "Prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontEnd.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "(این بخش ادیت نشود) Options",
            },
        ),
        migrations.CreateModel(
            name="fetures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                (
                    "Prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontEnd.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "(این بخش ادیت نشود) Options",
            },
        ),
    ]
