# Generated by Django 4.2.4 on 2023-08-23 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontEnd", "0007_product_specs_fetures"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fetures",
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "بخش ویژگی ها در صفحه محصول",
            },
        ),
        migrations.AlterModelOptions(
            name="specs",
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "بخش مشخصات در صفحه محصول",
            },
        ),
    ]
