# Generated by Django 4.2.4 on 2023-08-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontEnd", "0009_alter_fetures_options_alter_specs_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("img", models.ImageField(upload_to="digitalAssets/frontEnd/images")),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="division",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="frontEnd.division",
            ),
            preserve_default=False,
        ),
    ]
