# Generated by Django 4.2.4 on 2023-08-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontEnd", "0012_division_product_division"),
    ]

    operations = [
        migrations.AlterField(
            model_name="division",
            name="name",
            field=models.CharField(max_length=150, verbose_name="نام دسته بندی"),
        ),
    ]
