# Generated by Django 4.2.4 on 2023-08-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontEnd", "0013_alter_division_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="division",
            name="img",
            field=models.ImageField(
                upload_to="digitalAssets/frontEnd/images",
                verbose_name="تصویر دسته بندی",
            ),
        ),
        migrations.AlterField(
            model_name="fetures",
            name="item",
            field=models.CharField(max_length=100, verbose_name="ویژگی"),
        ),
        migrations.AlterField(
            model_name="product",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="frontEnd.division",
                verbose_name="یکی از تقسیم بندی ها رو انتخاب کنید",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(
                upload_to="digitalAssets/frontEnd/images", verbose_name="تصویر محصول"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="introduction",
            field=models.CharField(
                max_length=1500, verbose_name="درباره محصول (بخش معرفی)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="pricing",
            field=models.IntegerField(verbose_name="قیمت"),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=300, verbose_name="تایتل"),
        ),
        migrations.AlterField(
            model_name="specs",
            name="item",
            field=models.CharField(max_length=100, verbose_name="مشخصه"),
        ),
    ]
