# Generated by Django 3.2 on 2023-08-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0014_alter_division_img_alter_fetures_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'تقسیم بندی', 'verbose_name_plural': 'تقسیم بندی'},
        ),
    ]
