# Generated by Django 3.2 on 2023-08-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0016_alter_division_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'تقسیم بندی ها', 'verbose_name_plural': 'تقسیم بندی ها'},
        ),
    ]
