# Generated by Django 3.2 on 2023-08-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0019_auto_20230827_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدر'},
        ),
    ]
