# Generated by Django 3.2 on 2023-08-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0020_alter_slider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderdata',
            options={'verbose_name': 'اطلاعات اسلایدر'},
        ),
    ]
