# Generated by Django 3.2 on 2023-08-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0023_alter_sliderdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderdata',
            options={'verbose_name': 'اطلاعات اسلایدر', 'verbose_name_plural': 'اطلاعات اسلایدر'},
        ),
    ]
