# Generated by Django 3.2 on 2023-08-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0025_auto_20230827_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='Prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontEnd.product'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontEnd.division'),
        ),
    ]
