# Generated by Django 4.2.5 on 2023-11-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0003_prodimage'),
        ('frontEnd', '0027_auto_20230827_2014'),
    ]

    operations = [
    ]
