# Generated by Django 4.2.5 on 2023-11-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0028_merge_0003_prodimage_0027_auto_20230827_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='میزان تخفیف %'),
        ),
        migrations.AddField(
            model_name='product',
            name='subDivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontEnd.subdivision', verbose_name='(انتخابی) یکی از زیر تقسیم بندی ها رو انتخاب کنید'),
        ),
        migrations.AlterField(
            model_name='division',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='تصویر دسته بندی'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(upload_to='digitalAssets/frontEnd/images//', verbose_name='تصویر اسلایدر'),
        ),
    ]
