# Generated by Django 4.2.5 on 2023-12-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0029_remove_product_img_product_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductCode',
            field=models.IntegerField(default=0, verbose_name='کد محصول'),
            preserve_default=False,
        ),
    ]
